### ISSUE TITLE
Nil pointer dereference panic at cluster/swarm.(*Cluster).createContainer

### ISSUE THREAD

**Issue by wrotki** [docker/swarm#1081]
Running Swarm on two machines for a while (a couple hours, with a minor but constant load), I found the following nil pointer dereference panic in the logs. It looks like Engine.Create can return nil for an error, but also nil for a container -  it can happen when Engine.refreshContainer doesn’t pick up the newly created container, due to  a network hiccup perhaps.

Here’s the log (from swarm manage container):

time="2015-07-18T16:05:45Z" level=info msg="New leader elected: " 
time="2015-07-18T16:05:45Z" level=info msg="New leader elected: 54.204.78.44:3376" 
time="2015-07-18T16:05:45Z" level=info msg="Cluster leadership acquired" 
time="2015-07-18T16:05:46Z" level=error msg="HTTP error: No such container app_stateless_PolyWeb_6173736574736962298954567138918" status=404 
time="2015-07-18T16:05:46Z" level=error msg="HTTP error: No such image: app_stateless_PolyWeb_6173736574736962298954567138918" status=404 
time="2015-07-18T16:06:14Z" level=info msg="Cluster leadership lost" 
time="2015-07-18T16:06:14Z" level=info msg="New leader elected: " 
time="2015-07-18T16:06:14Z" level=error msg="HTTP error: No elected primary cluster manager" status=500 
time="2015-07-18T16:06:14Z" level=info msg="New leader elected: 54.221.38.147:3376" 
time="2015-07-18T16:06:32Z" level=error msg="Unable to update state of container \"02425a916ad7a942389b2baf18ad9189efb18af708ea78920524fd347c695c61\": Not found" id="R25B:WT45:XTNF:USYK:PX2V:GFG7:HYJX:VQZA:BYNV:YASA:ENTZ:U7MJ" name="ip-10-95-172-158" 
2015/07/18 16:06:32 http: panic serving 54.221.38.147:59256: runtime error: invalid memory address or nil pointer dereference
goroutine 225 [running]:
net/http.func·011()
/usr/src/go/src/net/http/server.go:1130 +0xbb
github.com/docker/swarm/cluster/swarm.(*Cluster).createContainer(0xc20800a4e0, 0xc208db1180, 0xc208d1c5bd, 0x35, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:136 +0x6d4
github.com/docker/swarm/cluster/swarm.(*Cluster).CreateContainer(0xc20800a4e0, 0xc208db1180, 0xc208d1c5bd, 0x35, 0x0, 0x0, 0x0)
/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:92 +0x77
github.com/docker/swarm/api.postContainersCreate(0xc208033ac0, 0x7fe0b445e098, 0xc2081e8820, 0xc208b36a90)
/go/src/github.com/docker/swarm/api/handlers.go:328 +0x2af
github.com/docker/swarm/api.func·008(0x7fe0b445e098, 0xc2081e8820, 0xc208b36a90)
/go/src/github.com/docker/swarm/api/primary.go:111 +0x2de
net/http.HandlerFunc.ServeHTTP(0xc2080b7400, 0x7fe0b445e098, 0xc2081e8820, 0xc208b36a90)
/usr/src/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080365f0, 0x7fe0b445e098, 0xc2081e8820, 0xc208b36a90)
/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc208031be0, 0x7fe0b445e098, 0xc2081e8820, 0xc208b36a90)
/go/src/github.com/docker/swarm/api/server.go:32 +0x9d
net/http.serverHandler.ServeHTTP(0xc208138840, 0x7fe0b445e098, 0xc2081e8820, 0xc208b36a90)
/usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081e8140)
/usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
/usr/src/go/src/net/http/server.go:1751 +0x35e
[ec2-user@ip-10-184-168-131 ~]$

**Comment by wrotki** [comment]
I'm preparing a Pull Request with a fix which I tested overnight on my swarm testbed.

**Comment by wrotki** [comment]
https://github.com/docker/swarm/pull/1082

**Comment by wrotki** [comment]
The fix was merged, closing
