### ISSUE TITLE
Jenkins swarm client | swarm-client-1.26-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by aku163** [docker/swarm#1130]
Hi ,

We are using swarm client swarm-client-1.26-jar-with-dependencies.jar to connect the slave node container with jenkins master container.
But it is observed often when we trigger the deployment job, it waits post connecting to the node.

==============================================================
Jenkins Logs :

```Started by user jenkins
[EnvInject] - Loading node environment variables.
Building remotely on INFRA-562_wasguest-7e4298fd (swarm WCS WCS-GUEST) in workspace /home/jenkins/workspace/PLATFORM-WCS-DEPLOY-LIVE
[EnvInject] - Executing scripts and injecting environment variables after the SCM step.
[EnvInject] - Injecting as environment variables the properties content 
ARTEFACT_SUFFIX=adhoc-${COPYARTIFACT_BUILD_NUMBER_PLATFORM_WCS_BUILD}
ARTEFACT_NAME=wcs-${ARTEFACT_SUFFIX}
[EnvInject] - Variables injected successfully.
[PLATFORM-WCS-DEPLOY-LIVE] $ /bin/sh -xe /tmp/hudson5614317773621594099.sh
+ rm -rf wcs-adhoc-70.tar.gz tmp
+ mkdir -p /home/jenkins/workspace/PLATFORM-WCS-DEPLOY-LIVE/tmp ```

:watch: 

We did delete the container node, a few secs later, it does connect to jenkins and below are the Swarm Client logs
==============================================================
Aug 7, 2015 9:03:24 AM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Attempting to connect to http://10.166.0.213:30053/ 8fea7c30-ca90-4962-99c9-5299ec0f1256 with ID 7e4298fd
Could not obtain CSRF crumb. Response code: 404
Aug 7, 2015 9:03:25 AM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Failed to create a slave on Jenkins CODE: 409
A slave called 'INFRA-562_wasguest-7e4298fd' is already created and on-line

Retrying in 10 seconds
Aug 7, 2015 9:03:35 AM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Attempting to connect to http://10.166.0.213:30053/ 8fea7c30-ca90-4962-99c9-5299ec0f1256 with ID 7e4298fd
Could not obtain CSRF crumb. Response code: 404
Aug 7, 2015 9:03:35 AM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Failed to create a slave on Jenkins CODE: 409
A slave called 'INFRA-562_wasguest-7e4298fd' is already created and on-line

Retrying in 10 seconds
Aug 7, 2015 9:03:45 AM org.apache.commons.httpclient.HttpMethodBase getResponseBody
WARNING: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Attempting to connect to http://10.166.0.213:30053/ 8fea7c30-ca90-4962-99c9-5299ec0f1256 with ID 7e4298fd
Could not obtain CSRF crumb. Response code: 404
Aug 7, 2015 9:03:45 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: INFRA-562_wasguest-7e4298fd
Aug 7, 2015 9:03:45 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Aug 7, 2015 9:03:45 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://10.166.0.213:30053/]
Aug 7, 2015 9:03:45 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 10.166.0.213:30054
Aug 7, 2015 9:03:45 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Aug 7, 2015 9:03:45 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
ava:707)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at hudson.plugins.swarm.SwarmClient.discoverFromMasterUrl(SwarmClient.java:191)
        at hudson.plugins.swarm.Client.run(Client.java:100)
        at hudson.plugins.swarm.Client.main(Client.java:74)
Retrying in 10 seconds
java.net.NoRouteToHostException: No route to host
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:385)
        at java.net.Socket.connect(Socket.java:546)
        at java.net.Socket.connect(Socket.java:495)
        at java.net.Socket.<init>(Socket.java:392)
        at java.net.Socket.<init>(Socket.java:266)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at hudson.plugins.swarm.SwarmClient.discoverFromMasterUrl(SwarmClient.java:191)
        at hudson.plugins.swarm.Client.run(Client.java:100)
        at hudson.plugins.swarm.Client.main(Client.java:74)
Retrying in 10 seconds

===================================================================
docker info
--------------------
Containers: 5
Images: 50
Storage Driver: devicemapper
 Pool Name: docker-202:1-1258291328-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 158 GB
 Data Space Total: 193.3 GB
 Data Space Available: 35.24 GB
 Metadata Space Used: 81.25 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.066 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 8
Total Memory: 14.28 GiB
Name: ip-10-166-0-213.eu-west-1.compute.internal
ID: PPUG:KCKR:SFCS:VQOO:JKJC:BAJX:RM6O:JM25:5ZWK:GKK7:HVA6:ZCRW
===================================================================
docker version
----------------------
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64
===================================================================


Any idea, if someone faced similar issue or have resolution to it ? Let me know if further information is needed

**Comment by chanwit** [comment]
Hi @aku163 
I am not sure it's within the scope of this project. Could you please report this to developers of the Hudson plugin. It's clearly a bug inside the plugin rather than `Swarm`.

**Comment by chanwit** [comment]
I think we can close this issue for now. Let me know if you still think it's related to Swarm.

**Comment by aku163** [comment]
We are still striving to get solution to it. Have raised the issue with jenkins.

Thanks.

**Comment by aehlke** [comment]
@aku163 any update with this? we are seeing something similar. thanks

**Comment by aehlke** [comment]
@aku163 would also appreciate a link to your ticket with jenkins / the swarm plugin, can't seem to find it

**Comment by aamol** [comment]
We did debug for the same but can't conclude if this is the issue with the swarm plugin or not. 

The deploy was stuck when it uses copy-artifact plugin. This is not even consistent for every deployment.

We did a workaround to wget instead of using the plugin.

Let me know if you find this info useful.
