### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by technolo-g** [docker/swarm#1334]
Hi guys,
 When attempting to deploy:
```
% dhost
tcp://bld-swarm-01:2375
(~) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- (pairing)
% docker run --rm -t -i ubuntu:latest
Post http://bld-swarm-01:2375/v1.20/containers/create: EOF.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

...against rc-1 we're getting these errors:

```
2015/10/23 20:05:10 http: panic serving 10.32.12.137:52020: runtime error: invalid memory address or nil pointer dereference
goroutine 4944618 [running]:
net/http.(*conn).serve.func1(0xc8207d82c0, 0x7fc41911a5e8, 0xc820020248)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/swarm/api.postContainersCreate(0xc8200eb780, 0x7fc4191265a8, 0xc820fd0c60, 0xc8202c2c40)
	/go/src/github.com/docker/swarm/api/handlers.go:404 +0x68b
github.com/docker/swarm/api.NewPrimary.func1(0x7fc4191265a8, 0xc820fd0c60, 0xc8202c2c40)
	/go/src/github.com/docker/swarm/api/primary.go:128 +0x300
net/http.HandlerFunc.ServeHTTP(0xc8203f9da0, 0x7fc4191265a8, 0xc820fd0c60, 0xc8202c2c40)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000ae60, 0x7fc4191265a8, 0xc820fd0c60, 0xc8202c2c40)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc8200ed270, 0x7fc4191265a8, 0xc820fd0c60, 0xc8202c2c40)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc8203381e0, 0x7fc4191265a8, 0xc820fd0c60, 0xc8202c2c40)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8207d82c0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

Here is some pertinent info:

### Docker Version
```
% docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        Thu Oct 15 09:12:56 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.16
 Go version:   go1.5.1
 Git commit:   fe88189
 Built:
 OS/Arch:      linux/amd64
```

## Docker Info
```
% docker info | sed 's/company info/generic info/g'
Containers: 140
Images: 347
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 23
 bld-docker-04.domain.com: bld-docker-04:4243
  └ Containers: 7
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=slow, dhost=bld-docker-04, disk=raid, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-05.domain.com: bld-docker-05:4243
  └ Containers: 33
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=slow, dhost=bld-docker-05, disk=raid, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-06.domain.com: bld-docker-06:4243
  └ Containers: 2
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=slow, dhost=bld-docker-06, disk=raid, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-07.domain.com: bld-docker-07:4243
  └ Containers: 9
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=slow, dhost=bld-docker-07, disk=raid, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-08.domain.com: bld-docker-08:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=slow, dhost=bld-docker-08, disk=raid, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-09.domain.com: bld-docker-09:4243
  └ Containers: 10
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 123.9 GiB
  └ Labels: cpu=slow, dhost=bld-docker-09, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-10.domain.com: bld-docker-10:4243
  └ Containers: 2
  └ Reserved CPUs: 0 / 25
  └ Reserved Memory: 0 B / 123.9 GiB
  └ Labels: cpu=fast, dhost=bld-docker-10, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-11.domain.com: bld-docker-11:4243
  └ Containers: 8
  └ Reserved CPUs: 0 / 25
  └ Reserved Memory: 0 B / 123.9 GiB
  └ Labels: cpu=fast, dhost=bld-docker-11, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-12.domain.com: bld-docker-12:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 123.9 GiB
  └ Labels: cpu=slow, dhost=bld-docker-12, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-13.domain.com: bld-docker-13:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 123.9 GiB
  └ Labels: cpu=slow, dhost=bld-docker-13, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-14.domain.com: bld-docker-14:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 25
  └ Reserved Memory: 0 B / 148.7 GiB
  └ Labels: cpu=fast, dhost=bld-docker-14, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-15.domain.com: bld-docker-15:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 123.9 GiB
  └ Labels: cpu=slow, dhost=bld-docker-15, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-16.domain.com: bld-docker-16:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=slow, dhost=bld-docker-16, disk=raid, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-17.domain.com: bld-docker-17:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-17, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-18.domain.com: bld-docker-18:4243
  └ Containers: 3
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-18, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-19.domain.com: bld-docker-19:4243
  └ Containers: 66
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-19, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-20.domain.com: bld-docker-20:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-20, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-21.domain.com: bld-docker-21:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-21, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-22.domain.com: bld-docker-22:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-22, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-23.domain.com: bld-docker-23:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-23, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-24.domain.com: bld-docker-24:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.3 GiB
  └ Labels: cpu=med, dhost=bld-docker-24, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-25.domain.com: bld-docker-25:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.1 GiB
  └ Labels: cpu=med, dhost=bld-docker-25, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
 bld-docker-26.domain.com: bld-docker-26:4243
  └ Containers: 0
  └ Reserved CPUs: 0 / 33
  └ Reserved Memory: 0 B / 198.1 GiB
  └ Labels: cpu=med, dhost=bld-docker-26, disk=single, executiondriver=native-0.2, kernelversion=3.13.0-66-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs, system=mycoolapp
CPUs: 735
Total Memory: 3.97 TiB
Name: 1902c86ef02a
```

Please let me know what other info I can provide

**Comment by technolo-g** [comment]
Swarm daemon info:

```
% docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
1902c86ef02a        swarm:1.0.0-rc1     "/swarm manage -H 0.0"   7 days ago          Up 7 days           0.0.0.0:2375->2375/tcp   compose_swarm_1
(~) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- (pairing)
% docker inspect 190
[
{
    "Id": "1902c86ef02a72460d53fc5982170043461365f0a6c8dffe8a2aee17c262cd1c",
    "Created": "2015-10-15T23:37:16.323287906Z",
    "Path": "/swarm",
    "Args": [
        "manage",
        "-H",
        "0.0.0.0:2375",
        "bld-docker-0[4:9]:4243,bld-docker-[10:26]:4243"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 8102,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-10-15T23:37:16.497132245Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "e94fe2dca9e5211dd6b70430c97c23c3c9f45a5d1b337e6a8a48cb4b02ff5b17",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "661262957bc3c105360605109f195deedad8bdf6bca3771d92e9019a6666779b",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:02",
        "NetworkID": "196914dc05b960761somenetworkidad35580a65f53aca68d7",
        "PortMapping": null,
        "Ports": {
            "2375/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "2375"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/1902c86ef02a",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/1902c86ef02a72460d53fc5982170043461365f0a6c8dffe8a2aee17c262cd1c/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/1902c86ef02a72460d53fc5982170043461365f0a6c8dffe8a2aee17c262cd1c/hostname",
    "HostsPath": "/var/lib/docker/containers/1902c86ef02a72460d53fc5982170043461365f0a6c8dffe8a2aee17c262cd1c/hosts",
    "LogPath": "/var/lib/docker/containers/1902c86ef02a72460d53fc5982170043461365f0a6c8dffe8a2aee17c262cd1c/1902c86ef02a72460d53fc5982170043461365f0a6c8dffe8a2aee17c262cd1c-json.log",
    "Name": "/compose_swarm_1",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/var/lib/docker/volumes/fdd7ffc6516b730bdbebc8ca23f901be55d96deb88e585b6b2b514680211183b/_data:/.swarm:rw"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "2375/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "2375"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "VolumesFrom": [],
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/var/lib/docker/volumes/fdd7ffc6516b730bdbebc8ca23f901be55d96deb88e585b6b2b514680211183b/_data",
            "Destination": "/.swarm",
            "Mode": "rw",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "1902c86ef02a",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "2375/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "affinity:container==b58b3e481daa9cf90932d4dbd1be86a137756bb1ef49d7e8d1693888e113889a",
            "SWARM_HOST=:2375"
        ],
        "Cmd": [
            "manage",
            "-H",
            "0.0.0.0:2375",
            "bld-docker-0[4:9]:4243,bld-docker-[10:26]:4243"
        ],
        "Image": "swarm:1.0.0-rc1",
        "Volumes": {
            "/.swarm": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": [
            "/swarm"
        ],
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash": "29d4604cd2d583somehashaaed57a6baaf7d5322d9ac735103e5",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "compose",
            "com.docker.compose.service": "swarm",
            "com.docker.compose.version": "1.3.1"
        }
    }
}
]
```

**Comment by vieux** [comment]
@technolo-g I think I know where it comes from, but I have one question.

Where you adding/removing nodes while scheduling containers ?

**Comment by technolo-g** [comment]
I don't believe so. Everything was static at the time. Nodes have been up/down/reinstalled repeatedly since Swarm was started though.

**Comment by vieux** [comment]
@technolo-g alright, that's the only place in the code where I could see the error happen, so we merged this one. Let's see if the error still happen with rc2 (to be released soon)

**Comment by technolo-g** [comment]
SGTM

**Comment by vlerenc** [comment]
Hit the same issue, will try the new RC.
