### ISSUE TITLE
Panic when creating new container with affinity

### ISSUE THREAD

**Issue by chosenken** [docker/swarm#1533]
I got the following panic when I attempted to create a new container using the API with different affinities specified.

```
2015/12/11 22:01:25 http: panic serving 207.67.107.174:63859: runtime error: index out of range
goroutine 731 [running]:
net/http.(*conn).serve.func1(0xc8200900b0, 0x7f5d96971030, 0xc820134190)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/swarm/scheduler/filter.(*AffinityFilter).Filter(0x130efe8, 0xc820788400, 0xc820337be0, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/scheduler/filter/affinity.go:37 +0x1365
github.com/docker/swarm/scheduler/filter.ApplyFilters(0xc820074a00, 0x5, 0x8, 0xc820788400, 0xc820337be0, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/swarm/scheduler/filter/filter.go:61 +0x12d
github.com/docker/swarm/scheduler.(*Scheduler).SelectNodesForContainer(0xc8200f62d0, 0xc820337b20, 0x3, 0x3, 0xc820788400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/scheduler/scheduler.go:37 +0xb3
github.com/docker/swarm/cluster/swarm.(*Cluster).createContainer(0xc82000b340, 0xc820788400, 0xc82074281d, 0x1a, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:153 +0x417
github.com/docker/swarm/cluster/swarm.(*Cluster).CreateContainer(0xc82000b340, 0xc820788400, 0xc82074281d, 0x1a, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:119 +0x60
github.com/docker/swarm/api.postContainersCreate(0xc8200eb900, 0x7f5d969c3418, 0xc820090a50, 0xc8200d6460)
	/go/src/github.com/docker/swarm/api/handlers.go:430 +0x2d2
github.com/docker/swarm/api.setupPrimaryRouter.func1(0x7f5d969c3418, 0xc820090a50, 0xc8200d6460)
	/go/src/github.com/docker/swarm/api/primary.go:151 +0x303
net/http.HandlerFunc.ServeHTTP(0xc8201ff7e0, 0x7f5d969c3418, 0xc820090a50, 0xc8200d6460)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000eeb0, 0x7f5d969c3418, 0xc820090a50, 0xc8200d6460)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc8200ed620, 0x7f5d969c3418, 0xc820090a50, 0xc8200d6460)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc820316e40, 0x7f5d969c3418, 0xc820090a50, 0xc8200d6460)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200900b0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

Version Info:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.1
 API version:  1.21
 Go version:   go1.5.2
 Git commit:   744e3a3
 Built:
 OS/Arch:      linux/amd64
```

The container I was trying to start had the following affinities specified:
```
constraint:pod==aws-us-east-1e-pod-01
affinity:container!=mongo_SwarmMongo12_Secondary
affinity:container!=mongo_SwarmMongo12_Arbiter
```

The containers ```mongo_SwarmMongo12_Secondary``` and ```mongo_SwarmMongo12_Arbiter``` were not created yet.  And the swarm hosts have the label ```aws-us-east-1e-pod-01``` specified.

**Comment by dongluochen** [comment]
@chosenken Thanks for reporting the issue! It looks similar to #1421.

**Comment by chosenken** [comment]
@dongluochen You may be right, I just checked and my swarm does indead of a "Dead" container.  Once I removed the dead container and restarted the swarm_master daemon I was able to create my containers again.

**Comment by dongluochen** [comment]
@chosenken I think swarm should fix the crash issue here.

**Comment by chosenken** [comment]
@dongluochen Yes, swarm does need to be able to handle dead containers when filtering on affinity/constraints.  The work around for now is to get rid of the dead containers, but if this was a production box I wouldn't be able to restart the docker daemon, so swarm would have to handle it.
