### ISSUE TITLE
Swarm crashes when engine removed (Consul discovery)

### ISSUE THREAD

**Issue by alexellis** [docker/swarm#1650]
I am finding that Swarm crashes on ARM when an engine is removed (Consul discovery)

See attached stack trace. 

Swarm/Docker version

```
clear ;docker info && docker version && docker run alexellis2/swarm-arm --version
Containers: 3
Images: 98
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-1-ARCH
Operating System: Arch Linux ARM (containerized)
CPUs: 4
Total Memory: 923.1 MiB
Name: docker2
ID: PHOV:TXBF:YD3Y:NBRW:ZSUH:G4K3:KHIP:XIKP:GIO7:O54S:LDLK:YBI6
WARNING: No memory limit support
WARNING: No swap limit support
Cluster store: consul://192.168.0.200:8500
Cluster advertise: 192.168.0.201:2375
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5-dirty
 Built:        Sat Jan 16 23:28:04 UTC 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5-dirty
 Built:        Sat Jan 16 23:28:04 UTC 2016
 OS/Arch:      linux/arm
swarm version 1.0.1 (HEAD)
```

```
panic: close of closed channel

goroutine 5 [running]:
github.com/docker/swarm/cluster.(*Engine).Disconnect(0x1118e790)
	/home/lud/go/src/github.com/docker/swarm/cluster/engine.go:193 +0x74
github.com/docker/swarm/cluster/swarm.(*Cluster).removeEngine(0x10e0c640, 0x11217c60, 0x12, 0x115d8900)
	/home/lud/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:295 +0xbc
github.com/docker/swarm/cluster/swarm.(*Cluster).monitorDiscovery(0x10e0c640, 0x10f26c00, 0x10f26c40)
	/home/lud/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:320 +0x1b0
created by github.com/docker/swarm/cluster/swarm.NewCluster
	/home/lud/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:86 +0x49c

goroutine 1 [chan receive, 21 minutes]:
github.com/docker/swarm/api.(*Server).ListenAndServe(0x10e0fbc0, 0x0, 0x0)
	/home/lud/go/src/github.com/docker/swarm/api/server.go:117 +0x310
github.com/docker/swarm/cli.manage(0x10f243f0)
	/home/lud/go/src/github.com/docker/swarm/cli/manage.go:332 +0x14e8
github.com/codegangsta/cli.Command.Run(0x8ba3b0, 0x6, 0x8b41d4, 0x1, 0x0, 0x0, 0x0, 0x925928, 0x17, 0x0, ...)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0xe18
github.com/codegangsta/cli.(*App).Run(0x10f40000, 0x10e620c0, 0x5, 0x6, 0x0, 0x0)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:176 +0xdc8
github.com/docker/swarm/cli.Run()
	/home/lud/go/src/github.com/docker/swarm/cli/cli.go:65 +0x444
main.main()
	/home/lud/go/src/github.com/docker/swarm/main.go:13 +0x14

goroutine 37 [IO wait, 2 minutes]:
net.runtime_pollWait(0x76dba1a0, 0x72, 0x10e60010)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10e5e938, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10e5e938, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10e5e900, 0x10fcc000, 0x1000, 0x1000, 0x0, 0x76df9018, 0x10e60010)
	/usr/lib/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10ef23e0, 0x10fcc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xc8
net/http.noteEOFReader.Read(0x76dba308, 0x10ef23e0, 0x10e9098c, 0x10fcc000, 0x1000, 0x1000, 0x1099b0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10ef4e50, 0x10fcc000, 0x1000, 0x1000, 0x10ef3208, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10eee8d0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10eee8d0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x10e90960)
	/usr/lib/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:685 +0xab4

goroutine 3 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc6cbe0)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/glog/glog.go:882 +0x60
created by github.com/golang/glog.init.1
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2cc

goroutine 4 [select]:
github.com/docker/docker/pkg/discovery/kv.(*Discovery).watchOnce(0x10eee180, 0x0, 0x10e5e440, 0x10f26c00, 0x10f26c40, 0x0)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/docker/docker/pkg/discovery/kv/kv.go:109 +0x45c
github.com/docker/docker/pkg/discovery/kv.(*Discovery).Watch.func1(0x10f26c00, 0x10f26c40, 0x10eee180, 0x0)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/docker/docker/pkg/discovery/kv/kv.go:164 +0x318
created by github.com/docker/docker/pkg/discovery/kv.(*Discovery).Watch
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/docker/docker/pkg/discovery/kv/kv.go:174 +0x90

goroutine 6 [sleep]:
time.Sleep(0x540be400, 0x2)
	/usr/lib/go/src/runtime/time.go:59 +0x104
github.com/docker/swarm/cluster/swarm.(*Cluster).monitorPendingEngines(0x10e0c640)
	/home/lud/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:337 +0x24
created by github.com/docker/swarm/cluster/swarm.NewCluster
	/home/lud/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:87 +0x4b8

goroutine 35 [IO wait]:
net.runtime_pollWait(0x76dba290, 0x72, 0x10e60010)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10ef9178, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10ef9178, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10ef9140, 0x10f5e000, 0x1000, 0x1000, 0x0, 0x76df9018, 0x10e60010)
	/usr/lib/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10ef2328, 0x10f5e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xc8
net/http.noteEOFReader.Read(0x76dba308, 0x10ef2328, 0x10efe56c, 0x10f5e000, 0x1000, 0x1000, 0x1099b0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10ef4bc0, 0x10f5e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10eee570)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10eee570, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x10efe540)
	/usr/lib/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:685 +0xab4

goroutine 36 [select]:
net/http.(*persistConn).writeLoop(0x10efe540)
	/usr/lib/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:686 +0xad0

goroutine 21 [select]:
net/http.(*persistConn).roundTrip(0x10efe540, 0x10e6cd78, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1164 +0x978
net/http.(*Transport).RoundTrip(0x10e728c0, 0x1119df80, 0xa0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:235 +0x428
net/http.send(0x1119df80, 0x76dfd320, 0x10e728c0, 0x1101bce0, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:220 +0x454
net/http.(*Client).send(0xc6c860, 0x1119df80, 0x59, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:143 +0x124
net/http.(*Client).doFollowingRedirects(0xc6c860, 0x1119df80, 0xa259c8, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:380 +0xa00
net/http.(*Client).Do(0xc6c860, 0x1119df80, 0x157c41a6, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:175 +0x98
github.com/hashicorp/consul/api.(*Client).doRequest(0x10e0ab40, 0x112ca210, 0x11119e58, 0x11119e6c, 0x1f, 0x0, 0x0)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/hashicorp/consul/api/api.go:368 +0xb4
github.com/hashicorp/consul/api.(*KV).getInternal(0x10e6c5a0, 0x10e0f6c0, 0x18, 0x10f500c0, 0x11119f88, 0x10f500c0, 0x10e01180, 0x0, 0x0)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/hashicorp/consul/api/kv.go:104 +0x1f4
github.com/hashicorp/consul/api.(*KV).List(0x10e6c5a0, 0x10e0f6c0, 0x18, 0x11119f88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/hashicorp/consul/api/kv.go:59 +0x100
github.com/docker/libkv/store/consul.(*Consul).WatchTree.func1(0x10e5e440, 0x0, 0x10e6c5a0, 0x10e0f6c0, 0x18)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul.go:341 +0xd8
created by github.com/docker/libkv/store/consul.(*Consul).WatchTree
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul.go:367 +0xc8

goroutine 52 [select, 2 minutes]:
github.com/docker/swarm/cluster.(*Engine).refreshLoop(0x10e92630)
	/home/lud/go/src/github.com/docker/swarm/cluster/engine.go:593 +0x700
created by github.com/docker/swarm/cluster.(*Engine).ValidationComplete
	/home/lud/go/src/github.com/docker/swarm/cluster/engine.go:257 +0xac

goroutine 62 [IO wait]:
net.runtime_pollWait(0x76db9d68, 0x72, 0x10e60010)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x1109a2b8, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x1109a2b8, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x1109a280, 0x11108000, 0x1000, 0x1000, 0x0, 0x76df9018, 0x10e60010)
	/usr/lib/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10ef2478, 0x11108000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xc8
net/http.noteEOFReader.Read(0x76dba308, 0x10ef2478, 0x110386ec, 0x11108000, 0x1000, 0x1000, 0x1099b0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x11598ab0, 0x11108000, 0x1000, 0x1000, 0x10ef2778, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x112ca4e0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x112ca4e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x110386c0)
	/usr/lib/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:685 +0xab4

goroutine 30 [select, 13 minutes]:
github.com/samalba/dockerclient.(*DockerClient).readJSONStream.func1(0x76dfd648, 0x10e62a20, 0x10e617a0, 0x10e5ed80, 0x10faa500)
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:280 +0x220
created by github.com/samalba/dockerclient.(*DockerClient).readJSONStream
	/home/lud/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:295 +0x70
```

**Comment by dongluochen** [comment]
@alexellis Is it the same set up as #1649? Did the removal of `docker3` cause the failure? 
```
 docker3: 192.168.0.202:2375
  └ Status: Healthy
  └ Containers: 16
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 969.2 MiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.13-1-ARCH, operatingsystem=Arch Linux ARM (containerized), storagedriver=aufs
  └ Error: Engine no longer exists
  └ UpdatedAt: 2016-01-18T12:17:39Z
```

**Comment by alexellis** [comment]
@dongluochen I think there are two separate issues. In this one the swarm manager actually terminated its process when swarm join was closed on docker3. In #1649 the manager did not terminate and the swarm join was still running - but in some unsynchronised manner.

**Comment by dongluochen** [comment]
@alexellis I think this has the same cause as #1649. The parallel validation on one engine could `disconnect` the engine in healthy state. When this engine is removed from discovery, swarm manager tries to `disconnect` it again and causes the crash.

**Comment by alexellis** [comment]
Glad you have figured it out. I can reproduce this every time - so I can rebuild the swarm binary for ARM and test a fix.

**Comment by dongluochen** [comment]
close via #1658.
