### ISSUE TITLE
panic on refreshcontainer

### ISSUE THREAD

**Issue by vieux** [docker/swarm#1805]
Sorry for the bad formatting, looks like there is a panic on `github.com/docker/swarm/cluster/engine.go:555`

```
{"log":"panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2016-02-11T02:14:44.771664068Z"}
{"log":"[signal 0xb code=0x1 addr=0x0 pc=0x45e3b0]\n","stream":"stderr","time":"2016-02-11T02:14:44.771709617Z"}
{"log":"\n","stream":"stderr","time":"2016-02-11T02:14:44.771720441Z"}
{"log":"goroutine 8248 [running]:\n","stream":"stderr","time":"2016-02-11T02:14:44.771728704Z"}
{"log":"github.com/docker/swarm/cluster.(*Engine).refreshContainer(0xc82663eb40, 0xc82bde3e00, 0x40, 0x1, 0x1, 0x0, 0x0)\n","stream":"stderr","time":"2016-02-11T02:14:44.771737767Z"}
{"log":"\u0009/go/src/github.com/docker/swarm/cluster/engine.go:555 +0x486\n","stream":"stderr","time":"2016-02-11T02:14:44.771747098Z"}
{"log":"github.com/docker/swarm/cluster.(*Engine).handler(0xc82663eb40, 0xc825f7e630, 0xc8274e9440, 0x0, 0x0, 0x0)\n","stream":"stderr","time":"2016-02-11T02:14:44.771756411Z"}
{"log":"\u0009/go/src/github.com/docker/swarm/cluster/engine.go:915 +0x157\n","stream":"stderr","time":"2016-02-11T02:14:44.771764571Z"}
{"log":"github.com/docker/swarm/cluster.(*Engine).(github.com/docker/swarm/cluster.handler)-fm(0xc825f7e630, 0xc8274e9440, 0x0, 0x0, 0x0)\n","stream":"stderr","time":"2016-02-11T02:14:\
44.771791816Z"}
{"log":"\u0009/go/src/github.com/docker/swarm/cluster/engine.go:160 +0x52\n","stream":"stderr","time":"2016-02-11T02:14:44.771800902Z"}
{"log":"github.com/samalba/dockerclient.(*DockerClient).StartMonitorEvents.func1(0xc826efdf20, 0xc8274e9440, 0xc824eb8100, 0x0, 0x0, 0x0)\n","stream":"stderr","time":"2016-02-11T02:14:\
44.7718086Z"}
{"log":"\u0009/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:510 +0x1b5\n","stream":"stderr","time":"2016-02-11T02:14:44.77181646\
4Z"}
{"log":"created by github.com/samalba/dockerclient.(*DockerClient).StartMonitorEvents\n","stream":"stderr","time":"2016-02-11T02:14:44.771824532Z"}
{"log":"\u0009/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:512 +0xa1\n","stream":"stderr","time":"2016-02-11T02:14:44.771832504\
Z"}
{"log":"\n","stream":"stderr","time":"2016-02-11T02:14:44.771840424Z"}
{"log":"goroutine 1 [chan receive, 487 minutes]:\n","stream":"stderr","time":"2016-02-11T02:14:44.771847521Z"}
{"log":"github.com/docker/swarm/api.(*Server).ListenAndServe(0xc82013d920, 0x0, 0x0)\n","stream":"stderr","time":"2016-02-11T02:14:44.771854904Z"}
{"log":"\u0009/go/src/github.com/docker/swarm/api/server.go:117 +0x383\n","stream":"stderr","time":"2016-02-11T02:14:44.77186257Z"}
{"log":"github.com/docker/swarm/cli.manage(0xc820073d40)\n","stream":"stderr","time":"2016-02-11T02:14:44.771870042Z"}
{"log":"\u0009/go/src/github.com/docker/swarm/cli/manage.go:332 +0x1c3a\n","stream":"stderr","time":"2016-02-11T02:14:44.771877424Z"}
```

**Comment by vieux** [comment]
ping @dongluochen
