### ISSUE TITLE
Panic on swarm 1.1.3

### ISSUE THREAD

**Issue by byrnedo** [docker/swarm#2098]
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   7e9c6bd
 Built:        Wed Mar  2 00:15:12 UTC 2016
 OS/Arch:      linux/amd64

I had been getting `Error response from daemon: Cannot connect to docker engine` when trying to run containers.

From the `swarm-agent-master` logs:
```
time="2016-04-08T08:34:43Z" level=error msg="HTTP error: Engine no longer exists" status=500 
time="2016-04-08T08:35:54Z" level=error msg="HTTP error: Engine no longer exists" status=500 
time="2016-04-08T08:38:53Z" level=error msg="HTTP error: Engine no longer exists" status=500 
2016/04/08 08:39:24 http: panic serving 10.0.11.18:38320: runtime error: invalid memory address or nil pointer dereference
goroutine 1281 [running]:
net/http.(*conn).serve.func1(0xc820641970, 0x7f5a553a89a8, 0xc8208c4840)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
net/http.(*Client).doFollowingRedirects(0x0, 0xc820604540, 0x10ce608, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:313 +0x6d
net/http.(*Client).Do(0x0, 0xc820604540, 0x1, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:178 +0x188
github.com/docker/swarm/api.proxyAsync(0xc820298a20, 0x7f5a553b0aa8, 0xc82064cdc0, 0xc820604540, 0xc820cd9960, 0x0, 0x0)
	/go/src/github.com/docker/swarm/api/utils.go:102 +0x3a5
github.com/docker/swarm/api.proxyContainerAndForceRefresh(0xc820134730, 0x7f5a553b0aa8, 0xc82064cdc0, 0xc820604540)
	/go/src/github.com/docker/swarm/api/handlers.go:1034 +0x254
github.com/docker/swarm/api.setupPrimaryRouter.func1(0x7f5a553b0aa8, 0xc82064cdc0, 0xc820604540)
	/go/src/github.com/docker/swarm/api/primary.go:154 +0x395
net/http.HandlerFunc.ServeHTTP(0xc82021e7c0, 0x7f5a553b0aa8, 0xc82064cdc0, 0xc820604540)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820134780, 0x7f5a553b0aa8, 0xc82064cdc0, 0xc820604540)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:103 +0x270
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc8200f5870, 0x7f5a553b0aa8, 0xc82064cdc0, 0xc820604540)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc82034a1e0, 0x7f5a553b0aa8, 0xc82064cdc0, 0xc820604540)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820641970)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/04/08 08:39:24 http: panic serving 10.0.11.18:38322: runtime error: invalid memory address or nil pointer dereference
goroutine 1282 [running]:
net/http.(*conn).serve.func1(0xc82064ce70, 0x7f5a553a89a8, 0xc8208c5b80)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
net/http.(*Client).doFollowingRedirects(0x0, 0xc820ad90a0, 0x10ce608, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:313 +0x6d
net/http.(*Client).Do(0x0, 0xc820ad90a0, 0x1, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:178 +0x188
github.com/docker/swarm/api.proxyAsync(0xc8203fefc0, 0x7f5a553b0aa8, 0xc8200abc30, 0xc820ad90a0, 0xc820cd9960, 0x0, 0x0)
	/go/src/github.com/docker/swarm/api/utils.go:102 +0x3a5
github.com/docker/swarm/api.proxyContainerAndForceRefresh(0xc820134730, 0x7f5a553b0aa8, 0xc8200abc30, 0xc820ad90a0)
	/go/src/github.com/docker/swarm/api/handlers.go:1034 +0x254
github.com/docker/swarm/api.setupPrimaryRouter.func1(0x7f5a553b0aa8, 0xc8200abc30, 0xc820ad90a0)
	/go/src/github.com/docker/swarm/api/primary.go:154 +0x395
net/http.HandlerFunc.ServeHTTP(0xc82021e7c0, 0x7f5a553b0aa8, 0xc8200abc30, 0xc820ad90a0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820134780, 0x7f5a553b0aa8, 0xc8200abc30, 0xc820ad90a0)
	/go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:103 +0x270
github.com/docker/swarm/api.(*dispatcher).ServeHTTP(0xc8200f5870, 0x7f5a553b0aa8, 0xc8200abc30, 0xc820ad90a0)
	/go/src/github.com/docker/swarm/api/server.go:32 +0x9f
net/http.serverHandler.ServeHTTP(0xc82034a1e0, 0x7f5a553b0aa8, 0xc8200abc30, 0xc820ad90a0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82064ce70)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

```

Restarting the swarm master container solved the issue for now.

**Comment by allencloud** [comment]
It seems a bug in Swarm.
In  https://github.com/docker/swarm/blob/v1.1.3/api/utils.go#L96-102, 
client may be nil, so when call the function `resp, err := client.Do(r)`, panic happens.

Here is the definition of function `HTTPClientAndScheme `
https://github.com/docker/swarm/blob/v1.1.3/cluster/engine.go#L141

**Comment by nishanttotla** [comment]
@byrnedo is this issue reproducible? And if so, could provide steps for it?

@allencloud's fix will likely fix it, but we'd like to make sure there isn't a deeper problem.

**Comment by dongluochen** [comment]
I suspect this is triggered when an Engine is removed from discovery. We set the Engine state to `disconnected` and remove clients. It looks there is a race condition when a disconnected node is still receiving requests. It matches this log. I think rejecting such request makes sense.

```
time="2016-04-08T08:38:53Z" level=error msg="HTTP error: Engine no longer exists" status=500 
```

**Comment by byrnedo** [comment]
I had just reached an open file limit before this happened on at least one of the hosts ( due to https://github.com/docker/docker/pull/20686) so I think that might make sense since the engine becomes totally unresponsive at that point.

@nishanttotla it probably is reproducible if I eat up the open file limit again, but I'm off on holidays from tomorrow so wont be able to try for a few weeks.
