### ISSUE TITLE
Swarm does not start in Nano Server TP5

### ISSUE THREAD

**Issue by StefanScherer** [docker/swarm#2293]
I've tried to put `swarm.exe` built with Go 1.5.4 into a `nanoserver` image on Windows Server 2016 TP5. My work in progress can be found here https://github.com/StefanScherer/dockerfiles-windows/pull/4

But the exe panics with

```
panic: Failed to load shell32.dll: The specified module could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0xc082030ae0)
        c:/go/src/syscall/dll_windows.go:280 +0x6a
syscall.(*LazyProc).Addr(0xc082030ae0, 0x7ff804e68e40)
        c:/go/src/syscall/dll_windows.go:287 +0x28
syscall.CommandLineToArgv(0x1e81762, 0xc08202bdec, 0x1, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:885 +0x3c
os.init.1()
        c:/go/src/os/exec_windows.go:100 +0x4a
os.init()
        c:/go/src/os/types_windows.go:107 +0x303
fmt.init()
        c:/go/src/fmt/scan.go:1195 +0x5d
github.com/docker/swarm/vendor/github.com/docker/docker/pkg/discovery/file.init()
        C:/Go/src/github.com/docker/swarm/vendor/github.com/docker/docker/pkg/discovery/file/file.go:109 +0x42
main.init()
        C:/Go/src/github.com/docker/swarm/main.go:14 +0x42
```

There is a workaround in Docker Engine to explicit load the shell32.dll 
https://github.com/docker/docker/commit/fa82c0aa10cfac8c6d5e2446876dc79b2b0c1bf9

So probably we need something like this in Swarm to workaround the issue in Go 1.5.4, 1.6.1, 1.6.2.
This may be fixed with Go 1.7 https://go-review.googlesource.com/#/c/22054/

**Comment by StefanScherer** [comment]
Fixed in newer versions.
