### ISSUE TITLE
Swarm/docker version conflict

### ISSUE THREAD

**Issue by alktlr** [docker/swarm#245]
Yet another issue with [Jenkins Docker plugin] (https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin). The version number in /version is the swarm version number where the docker plugin expect it to be the docker version number. It is possible to set the swarm version to SwarmVersion and pass-through the docker version.

Docker plugin exception
Caused by: java.lang.NumberFormatException: For input string: "swarm/0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:449)
	at java.lang.Integer.parseInt(Integer.java:499)
	at com.nirima.docker.client.model.Version.getVersionComponents(Version.java:45)
	at com.nirima.jenkins.plugins.docker.DockerCloud$DescriptorImpl.doTestConnection(DockerCloud.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)
	... 56 more

**Comment by phemmer** [comment]
I don't think it feasible to pass-through the docker version.
Firstly, the docker servers might not be running the same version.
Secondly, the swarm API is not exactly the same as the docker API. Some things are currently missing, and others are implemented differently (`docker info` responds with a list of nodes when run against swarm, `docker ps` prefixes the node names with the node ID).
Both these things might break a client if they receive something they weren't expecting.

**Comment by vieux** [comment]
I agree with @phemmer it's not really possible to put the docker version.

@alktlr does the plugin uses the version in anyway ?
It's crashing because the current version is swarm/0.0.1 (not a number)
Docker can have version 1.4.1-dev and the plugin isn't crashing.

What about we put 0.0.1 (swarm) as version ? I'm pretty sure it won't crash.
Can you test that ?

**Comment by alktlr** [comment]
I have looked at the code and 1.4.1-dev would also fail. It creates an array split by dots and parses each element to an int. I use 1.4.1.

```java
public int[] getVersionComponents() {
String[] v = StringUtils.split(getVersion(), ".");
int[] result = new int[v.length];
for(int i=0; i<v.length;i++) {
    result[i] = Integer.parseInt(v[i]);
}
return result;
}
```

The docker plugin will only accept version 1 or higher.

```java
if( version.getVersionComponents()[0] < 1 )
                return FormValidation.error("Docker host is " + version.getVersion() + " which is not supported.");
```

The good news is that the version verification step can easily be bypassed by saving configuration without testing the connection. But then ran into a not implemented feature. (not to hijack this issue)

`level=info msg="GET /images/json?filter=<docker image>&all=true"`
`level=error msg="Not supported in clustering mode."`

**Comment by vieux** [comment]
ok, I believe we should fix the plugin itself, because if it doesn't work with `1.4.1-dev` it means it only works with stable versions, not master.

Anyway, yes, swarm doesn't support `docker images`

We will add it, we just need to figure out how to do it. (I'll make a proposal soon)

**Comment by vieux** [comment]
@alktlr see #249

**Comment by vieux** [comment]
I'm closing this one. Feel free to comment in #249
