### ISSUE TITLE
Swarm crashed with panic 'runtime error: slice bounds out of range`

### ISSUE THREAD

**Issue by skryzhny** [docker/swarm#2624]
`swarm:1.2.6`

After upgrading to swarm standalone 1.2.6 I'm getting these errors:
```
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: panic: runtime error: slice bounds out of range
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]:
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: goroutine 163 [running]:
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: panic(0xc0f820, 0xc420010090)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: bufio.(*Writer).flush(0xc42319eb80, 0x55a, 0xc424d6f780)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/bufio/bufio.go:563 +0x1b5
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: bufio.(*Writer).Flush(0xc42319eb80, 0x1, 0x7fb895a2f080)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/bufio/bufio.go:552 +0x2b
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: net/http.(*response).Flush(0xc4256441a0)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/net/http/server.go:1403 +0x37
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/api.(*eventsHandler).Handle(0xc420127c50, 0xc423dec200, 0xc424d6fab8, 0x0)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/api/events.go:120 +0x9b7
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*EventHandlers).Handle(0xc42012d040, 0xc423dec200)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/event.go:42 +0xe9
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster/swarm.(*Cluster).Handle(0xc420322f50, 0xc423dec200, 0x40, 0x0)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:118 +0x39
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*Engine).handler(0xc420140c60, 0xc421976600, 0x1b, 0xc42133ab80, 0x40, 0xc42060ed20, 0x55, 0xc4213ed620, 0x9, 0xc421976620, ...)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/engine.go:1304 +0x1bc
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*Engine).(github.com/docker/swarm/cluster.handler)-fm(0xc421976600, 0x1b, 0xc42133ab80, 0x40, 0xc42060ed20, 0x55, 0xc4213ed620, 0x9, 0xc421976620, 0x1b, ...)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/engine.go:234 +0x69
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*EventsMonitor).Start.func1(0xc4201368c0, 0xc4202a78c0, 0xc420516c60, 0xc4202a77a0, 0xc4202a7920)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/event_monitor.go:36 +0x1a1
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: created by github.com/docker/swarm/cluster.(*EventsMonitor).Start
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/event_monitor.go:48 +0x121
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: panic: runtime error: slice bounds out of range
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]:
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: goroutine 222 [running]:
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: panic(0xc0f820, 0xc420010090)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: bufio.(*Writer).flush(0xc42319eb80, 0x577, 0xc423819780)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/bufio/bufio.go:563 +0x1b5
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: bufio.(*Writer).Flush(0xc42319eb80, 0x1, 0x7fb895a2f080)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/bufio/bufio.go:552 +0x2b
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: net/http.(*response).Flush(0xc4256441a0)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/usr/local/go/src/net/http/server.go:1403 +0x37
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/api.(*eventsHandler).Handle(0xc420127c50, 0xc421cf8e00, 0xc423819ab8, 0x0)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/api/events.go:120 +0x9b7
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*EventHandlers).Handle(0xc42012d040, 0xc421cf8e00)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/event.go:42 +0xe9
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster/swarm.(*Cluster).Handle(0xc420322f50, 0xc421cf8e00, 0x40, 0x0)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/swarm/cluster.go:118 +0x39
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*Engine).handler(0xc420140dc0, 0xc42137b540, 0x1b, 0xc421c4d180, 0x40, 0xc42241f860, 0x53, 0xc42140deb0, 0x9, 0xc42137b560, ...)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/engine.go:1304 +0x1bc
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*Engine).(github.com/docker/swarm/cluster.handler)-fm(0xc42137b540, 0x1b, 0xc421c4d180, 0x40, 0xc42241f860, 0x53, 0xc42140deb0, 0x9, 0xc42137b560, 0x1b, ...)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/engine.go:234 +0x69
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: github.com/docker/swarm/cluster.(*EventsMonitor).Start.func1(0xc420454630, 0xc420464a20, 0xc420133840, 0xc4204648a0, 0xc420464a80)
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/event_monitor.go:36 +0x1a1
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: created by github.com/docker/swarm/cluster.(*EventsMonitor).Start
2017-02-06T15:25:42+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: #011/go/src/github.com/docker/swarm/cluster/event_monitor.go:48 +0x121
2017-02-06T15:25:43+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: time="2017-02-06T15:25:43Z" level=info msg="Listening for HTTP" addr="0.0.0.0:2375" proto=tcp
```
We updated in hope to fix issues described in https://github.com/docker/swarm/issues/2581
While stacktraces is much shorter now and panics less frequent, we still have them.
It may be unrelated but after panic I see one of nodes is in hang state, `ps ax' command hangs on node and node isn't show in swarm logs as registered one.
Excerpt from logs about bad node:
```
2017-02-08T07:44:27+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: time="2017-02-08T07:44:27Z" level=error msg="HTTP error: Get http://HOSTNAME:2375/v1.20/containers/b570ea23fab12e6c5e2bffb9aecdfb6f97a9031c82768952eac9df39689fd446/logs?stdout=1&stderr=1&follow=1&since=1486539267: net/http: request canceled" status=500 
2017-02-08T07:47:13+00:00 ip-172-19-0-1.ec2.internal docker/602b814d5969[19728]: time="2017-02-08T07:47:13Z" level=error msg="HTTP error: Get http://HOSTNAME:2375/v1.20/containers/1364de9d617d8d7ee22ec203344d0b5ee3d6717a08715f7ae57b28245fe9eb46/logs?stdout=1&stderr=1&follow=1&since=1486539433: net/http: request canceled" status=500
```

Attaching logs produced with `grep -v "level=" swarm.log >swarm.log-out` command.
[swarm.log-20170208.zip](https://github.com/docker/swarm/files/760403/swarm.log-20170208.zip)

**Comment by skryzhny** [comment]
After nodes update to docker `17.04.0-ce, build 4845c56` errors become like 10 times less frequent, only got this one for about week of running:
```
time="2017-05-01T10:56:01Z" level=warning msg="Engine (ID: 3J3A:OBHH:3FBV:VIP6:TYY4:EVSD:4MSC:52R4:DSOV:6UIC:5WBZ:ZVHB, Addr: ***.****.***:2375) has unsynchronized systime with swarm, please synchronize it." 
panic: runtime error: slice bounds out of range

goroutine 3228 [running]:
panic(0xc0f820, 0xc4200100a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
bufio.(*Writer).Write(0xc420cd4900, 0x10f401e, 0x2, 0x2, 0x800, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:597 +0x135
net/http.(*chunkWriter).Write(0xc42026a788, 0xc421a39000, 0x800, 0x800, 0xc420ac1640, 0x42a19c, 0xc420ac1650)
        /usr/local/go/src/net/http/server.go:326 +0x168
bufio.(*Writer).flush(0xc4209e1640, 0xc421a38000, 0x154)
        /usr/local/go/src/bufio/bufio.go:563 +0x75
bufio.(*Writer).Write(0xc4209e1640, 0xc421a38000, 0x6ac, 0x800, 0x0, 0x6ac, 0x1113d50)
        /usr/local/go/src/bufio/bufio.go:599 +0xd6
net/http.(*response).write(0xc42026a750, 0x6ac, 0xc421a38000, 0x6ac, 0x800, 0x0, 0x0, 0xceea00, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1339 +0x140
net/http.(*response).Write(0xc42026a750, 0xc421a38000, 0x6ac, 0x800, 0x0, 0x0, 0xc421dbe800)
        /usr/local/go/src/net/http/server.go:1311 +0x64
fmt.Fprintf(0x10f7380, 0xc42026a750, 0xc421dbe800, 0x6ac, 0x0, 0x0, 0x0, 0xc42185e930, 0x6c, 0xc421bc6340)
        /usr/local/go/src/fmt/print.go:182 +0xa9
github.com/docker/swarm/api.(*eventsHandler).Handle(0xc4203108d0, 0xc421922a00, 0xc420ac1ab8, 0x0)
        /go/src/github.com/docker/swarm/api/events.go:113 +0x819
github.com/docker/swarm/cluster.(*EventHandlers).Handle(0xc4202bb6a0, 0xc421922a00)
        /go/src/github.com/docker/swarm/cluster/event.go:42 +0xe9
github.com/docker/swarm/cluster/swarm.(*Cluster).Handle(0xc4202d7960, 0xc421922a00, 0x40, 0x0)
        /go/src/github.com/docker/swarm/cluster/swarm/cluster.go:118 +0x39
github.com/docker/swarm/cluster.(*Engine).handler(0xc4203b66e0, 0xc421bcb6b0, 0x2d, 0xc420ed71c0, 0x40, 0xc4220d3b60, 0x55, 0xc4215005b0, 0x9, 0xc421bcb6e0, ...)
        /go/src/github.com/docker/swarm/cluster/engine.go:1304 +0x1bc
github.com/docker/swarm/cluster.(*Engine).(github.com/docker/swarm/cluster.handler)-fm(0xc421bcb6b0, 0x2d, 0xc420ed71c0, 0x40, 0xc4220d3b60, 0x55, 0xc4215005b0, 0x9, 0xc421bcb6e0, 0x2d, ...)
        /go/src/github.com/docker/swarm/cluster/engine.go:234 +0x69
github.com/docker/swarm/cluster.(*EventsMonitor).Start.func1(0xc420324fe0, 0xc421ade0c0, 0xc4216acda0, 0xc420a75f80, 0xc421ade120)
        /go/src/github.com/docker/swarm/cluster/event_monitor.go:36 +0x1a1
created by github.com/docker/swarm/cluster.(*EventsMonitor).Start
        /go/src/github.com/docker/swarm/cluster/event_monitor.go:48 +0x121
panic: runtime error: slice bounds out of range

goroutine 4549 [running]:
panic(0xc0f820, 0xc4200100a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
bufio.(*Writer).flush(0xc420cd4900, 0x800, 0x0)
        /usr/local/go/src/bufio/bufio.go:569 +0x177
bufio.(*Writer).Flush(0xc420cd4900, 0xc4209e1640, 0x0)
        /usr/local/go/src/bufio/bufio.go:552 +0x2b
net/http.(*chunkWriter).flush(0xc42026a788)
        /usr/local/go/src/net/http/server.go:338 +0x3d
net/http.(*response).Flush(0xc42026a750)
        /usr/local/go/src/net/http/server.go:1404 +0x49
github.com/docker/swarm/api.(*eventsHandler).Handle(0xc4203108d0, 0xc42106b000, 0xc421e07ab8, 0x0)
        /go/src/github.com/docker/swarm/api/events.go:120 +0x9b7
github.com/docker/swarm/cluster.(*EventHandlers).Handle(0xc4202bb6a0, 0xc42106b000)
        /go/src/github.com/docker/swarm/cluster/event.go:42 +0xe9
github.com/docker/swarm/cluster/swarm.(*Cluster).Handle(0xc4202d7960, 0xc42106b000, 0x40, 0x0)
        /go/src/github.com/docker/swarm/cluster/swarm/cluster.go:118 +0x39
github.com/docker/swarm/cluster.(*Engine).handler(0xc4203b66e0, 0xc421fc75f0, 0x2d, 0xc421e20380, 0x40, 0xc421c34000, 0x55, 0xc4214980a0, 0x9, 0xc421fc7620, ...)
        /go/src/github.com/docker/swarm/cluster/engine.go:1304 +0x1bc
github.com/docker/swarm/cluster.(*Engine).(github.com/docker/swarm/cluster.handler)-fm(0xc421fc75f0, 0x2d, 0xc421e20380, 0x40, 0xc421c34000, 0x55, 0xc4214980a0, 0x9, 0xc421fc7620, 0x2d, ...)
        /go/src/github.com/docker/swarm/cluster/engine.go:234 +0x69
github.com/docker/swarm/cluster.(*EventsMonitor).Start.func1(0xc4217f0ff0, 0xc42180d8c0, 0xc420f6f140, 0xc42180d7a0, 0xc42180d920)
        /go/src/github.com/docker/swarm/cluster/event_monitor.go:36 +0x1a1
created by github.com/docker/swarm/cluster.(*EventsMonitor).Start
        /go/src/github.com/docker/swarm/cluster/event_monitor.go:48 +0x121
time="2017-05-01T11:03:23Z" level=info msg="Listening for HTTP" addr="0.0.0.0:2375" proto=tcp
```

BTW, we have NTPD daemon running on all hosts, any ideas why system time difference reported?

**Comment by allencloud** [comment]
Any update on this? @dongluochen 
I think it is very often for us to  run into such kind of crash.

**Comment by dongluochen** [comment]
The crash was fixed by https://github.com/docker/swarm/pull/2652.

**Comment by dongluochen** [comment]
@skryzhny 

> BTW, we have NTPD daemon running on all hosts, any ideas why system time difference reported?

Swarm manager compares the node's reported system time with its own clock. If the difference is larger than a second. It'd report the node's clock not synchronized. Can you validate the node's reported "SystemTime" like this?

```
curl http://node:port/info 
"SystemTime":"2017-05-25T15:23:58.606782284-07:00"
```
