### ISSUE TITLE
Panic in github.com/docker/swarm/cluster.(*Engine).UpdateNetworkContainers

### ISSUE THREAD

**Issue by tisoft** [docker/swarm#2754]
I am running docker legacy swarm manager as a service in a docker swarm mode cluster. The legacy swarm manager is restarted every minute after the following panic:

```
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | panic: assignment to entry in nil map
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | 
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | goroutine 274 [running]:
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | panic(0xc2b7c0, 0xc4203448f0)
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | github.com/docker/swarm/cluster.(*Engine).UpdateNetworkContainers(0xc4203849a0, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | 	/go/src/github.com/docker/swarm/cluster/engine.go:1025 +0x3ca
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | github.com/docker/swarm/cluster.(*Engine).refreshLoop(0xc4203849a0)
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | 	/go/src/github.com/docker/swarm/cluster/engine.go:949 +0x605
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | created by github.com/docker/swarm/cluster.(*Engine).ValidationComplete
swarm-master.1.uvuzsekbrpxt@ukwtsvulx157.redacted.com    | 	/go/src/github.com/docker/swarm/cluster/engine.go:365 +0xab
```

Despite this error using the docker legacy swarm inside the docker swarm mode is working fine for my use case (starting jenkins one-off build slaves).

swarm version:
```
Server:
 Version:      swarm/1.2.7
 API version:  1.22 (minimum version )
 Go version:   go1.7.1
 Git commit:   2005aec
 Built:        2017-06-30T22:13:10+0000
 OS/Arch:      linux/amd64
 Experimental: false
```

docker version:
```
Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by allencloud** [comment]
Thanks for your feedback. I have posted a PR  https://github.com/docker/swarm/pull/2755 to try to fix this. PTAL
