### ISSUE TITLE
Runtime error when getting system information

### ISSUE THREAD

**Issue by evoevodin** [docker/swarm#560]
I can't reproduce it but anyway.

```
INFO[602216] HTTP request received                         method=GET uri=/info
2015/04/01 11:42:51 http: panic serving 172.30.1.251:50406: runtime error: invalid memory address or nil pointer dereference
goroutine 175192 [running]:
net/http.func·011()
        /usr/lib/golang/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7be800, 0xa299d3)
        /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/swarm/cluster/swarm.(*node).UsedCpus(0xc20802add0, 0x2)
        /root/gocode/src/github.com/docker/swarm/cluster/swarm/node.go:339 +0x98
github.com/docker/swarm/cluster/swarm.(*Cluster).Info(0xc20801ab90, 0x0, 0x0, 0x0)
        /root/gocode/src/github.com/docker/swarm/cluster/swarm/cluster.go:263 +0x4e7
github.com/docker/swarm/api.getInfo(0xc2080883f0, 0x7f01fd5c3620, 0xc208392640, 0xc208350750)
        /root/gocode/src/github.com/docker/swarm/api/api.go:45 +0xa2
github.com/docker/swarm/api.func·002(0x7f01fd5c3620, 0xc208392640, 0xc208350750)
        /root/gocode/src/github.com/docker/swarm/api/api.go:489 +0x2a0
net/http.HandlerFunc.ServeHTTP(0xc20803eaa0, 0x7f01fd5c3620, 0xc208392640, 0xc208350750)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20801abe0, 0x7f01fd5c3620, 0xc208392640, 0xc208350750)
        /root/gocode/src/github.com/gorilla/mux/mux.go:98 +0x292
net/http.serverHandler.ServeHTTP(0xc208114ae0, 0x7f01fd5c3620, 0xc208392640, 0xc208350750)
        /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208450c80)
        /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
```

* CentOS 7
* Docker version 1.4.1
* Swarm version 0.2.0-rc1

And i had the same problem dealing with swarm 0.1.0

```
INFO[602216] HTTP request received                         method=GET uri=/info
2015/04/01 11:42:51 http: panic serving 172.30.1.251:50404: runtime error: invalid memory address or nil pointer dereference
goroutine 175191 [running]:
net/http.func·011()
        /usr/lib/golang/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7be800, 0xa299d3)
        /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/swarm/cluster/swarm.(*node).UsedCpus(0xc20802add0, 0x2)
        /root/gocode/src/github.com/docker/swarm/cluster/swarm/node.go:339 +0x98
github.com/docker/swarm/cluster/swarm.(*Cluster).Info(0xc20801ab90, 0x0, 0x0, 0x0)
        /root/gocode/src/github.com/docker/swarm/cluster/swarm/cluster.go:263 +0x4e7
github.com/docker/swarm/api.getInfo(0xc2080883f0, 0x7f01fd5c3620, 0xc208392500, 0xc208350680)
        /root/gocode/src/github.com/docker/swarm/api/api.go:45 +0xa2
github.com/docker/swarm/api.func·002(0x7f01fd5c3620, 0xc208392500, 0xc208350680)
        /root/gocode/src/github.com/docker/swarm/api/api.go:489 +0x2a0
net/http.HandlerFunc.ServeHTTP(0xc20803eaa0, 0x7f01fd5c3620, 0xc208392500, 0xc208350680)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20801abe0, 0x7f01fd5c3620, 0xc208392500, 0xc208350680)
        /root/gocode/src/github.com/gorilla/mux/mux.go:98 +0x292
net/http.serverHandler.ServeHTTP(0xc208114ae0, 0x7f01fd5c3620, 0xc208392500, 0xc208350680)
        /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208450c00)
        /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by elferink** [comment]
I think we encountered the same problem, for us the problem happend when getting UsedMemory as we don't use the CpuShares.
We also use swarm on a CentOS 7 server, our swarm exists of CoreOS clients.

* CentOS 7 (swarm server)
* CoreOS stable (607.0.0) (swarm clients)
* Docker version 1.5.0, build a8a31ef-dirty
* Swarm version 9f8ba511

```
apr 03 09:40:28 reaper swarm[5639]: 2015/04/03 09:40:28 http: panic serving 192.168.56.103:44559: runtime error: invalid memory address or nil pointer dereference
apr 03 09:40:28 reaper swarm[5639]: goroutine 52783 [running]:
apr 03 09:40:28 reaper swarm[5639]: net/http.func·011()
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/golang/src/pkg/net/http/server.go:1100 +0xb7
apr 03 09:40:28 reaper swarm[5639]: runtime.panic(0x7c2b80, 0xa319f3)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
apr 03 09:40:28 reaper swarm[5639]: github.com/docker/swarm/cluster/swarm.(*node).UsedMemory(0xc20810a5b0, 0x10)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/docker/swarm/cluster/swarm/node.go:334 +0x98
apr 03 09:40:28 reaper swarm[5639]: github.com/docker/swarm/scheduler/strategy.weighNodes(0xc2081af200, 0xc20841dc80, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/docker/swarm/scheduler/strategy/weighted_node.go:56 +0x220
apr 03 09:40:28 reaper swarm[5639]: github.com/docker/swarm/scheduler/strategy.(*SpreadPlacementStrategy).PlaceContainer(0xa370b0, 0xc2081af200, 0xc20841dc80, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/docker/swarm/scheduler/strategy/spread.go:21 +0x8e
apr 03 09:40:28 reaper swarm[5639]: github.com/docker/swarm/scheduler.(*Scheduler).SelectNodeForContainer(0xc2080a2d50, 0xc20841dc00, 0x5, 0x8, 0xc2081af200, 0x0, 0x0, 0x0, 0x0)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/docker/swarm/scheduler/scheduler.go:31 +0x16c
apr 03 09:40:28 reaper swarm[5639]: github.com/docker/swarm/cluster/swarm.(*Cluster).CreateContainer(0xc2080305f0, 0xc2081af200, 0xc20812ce1d, 0x40, 0x0, 0x0, 0x0)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/docker/swarm/cluster/swarm/cluster.go:77 +0xfe
apr 03 09:40:28 reaper swarm[5639]: github.com/docker/swarm/api.postContainersCreate(0xc2080a36b0, 0x7f2571ebbfd8, 0xc208188960, 0xc208176820)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/docker/swarm/api/api.go:218 +0x472
apr 03 09:40:28 reaper swarm[5639]: github.com/docker/swarm/api.func·002(0x7f2571ebbfd8, 0xc208188960, 0xc208176820)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/docker/swarm/api/api.go:530 +0x2a0
apr 03 09:40:28 reaper swarm[5639]: net/http.HandlerFunc.ServeHTTP(0xc2080fa880, 0x7f2571ebbfd8, 0xc208188960, 0xc208176820)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
apr 03 09:40:28 reaper swarm[5639]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc208030640, 0x7f2571ebbfd8, 0xc208188960, 0xc208176820)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/docker-swarm/src/github.com/gorilla/mux/mux.go:98 +0x292
apr 03 09:40:28 reaper swarm[5639]: net/http.serverHandler.ServeHTTP(0xc208083740, 0x7f2571ebbfd8, 0xc208188960, 0xc208176820)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
apr 03 09:40:28 reaper swarm[5639]: net/http.(*conn).serve(0xc20841d900)
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
apr 03 09:40:28 reaper swarm[5639]: created by net/http.(*Server).Serve
apr 03 09:40:28 reaper swarm[5639]: /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by aluzzardi** [comment]
Thanks @evoevodin and @elferink.

This is a rare race condition that happens if we run a `docker info` right after we detect a new container **before** we get a chance to do an inspect - the crash window is in the order of a few milliseconds.
