### ISSUE TITLE
Affinity filter crashing

### ISSUE THREAD

**Issue by vbichov** [docker/swarm#762]
Running this command:

```bash
swarm run -d -e affinity:container!="registrator*" --net="host" --name registrator1 -v /var/run/docker.sock:/tmp/docker.sock progrium/registrator consul://16.59.63.129:8500
```

Getting:

```
FATA[0004] Error response from daemon: Network Error. A communication error occurred: 
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time. For assistance, contact your network support team.
```

**docker logs swarm**:

```
time="2015-05-10T14:11:31Z" level=info msg="HTTP request received" method=POST uri="/v1.18/containers/create?name=registrator1"
2015/05/10 14:11:31 http: panic serving 16.42.57.11:51311: runtime error: index out of range
goroutine 521 [running]:
net/http.func·011()
        /usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7befe0, 0xa2929c)
        /usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/swarm/scheduler/filter.(*AffinityFilter).Filter(0xa2dea8, 0xc2081e9a00, 0xc20820b600, 0x9, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/swarm/scheduler/filter/affinity.go:37 +0xacc
github.com/docker/swarm/scheduler/filter.ApplyFilters(0xc20804e700, 0x5, 0x8, 0xc2081e9a00, 0xc20820b600, 0x9, 0x10, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/swarm/scheduler/filter/filter.go:61 +0x14b
github.com/docker/swarm/scheduler.(*Scheduler).SelectNodeForContainer(0xc208076300, 0xc20820b600, 0x9, 0x10, 0xc2081e9a00, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/swarm/scheduler/scheduler.go:31 +0xb2
github.com/docker/swarm/cluster/swarm.(*Cluster).CreateContainer(0xc208018d20, 0xc2081e9a00, 0xc2081e2a23, 0xc, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/swarm/cluster/swarm/cluster.go:73 +0x106
github.com/docker/swarm/api.postContainersCreate(0xc2080764b0, 0x7f2e30d47dd0, 0xc208116780, 0xc208278dd0)
        /go/src/github.com/docker/swarm/api/api.go:218 +0x472
github.com/docker/swarm/api.func·002(0x7f2e30d47dd0, 0xc208116780, 0xc208278dd0)
        /go/src/github.com/docker/swarm/api/api.go:553 +0x2a0
net/http.HandlerFunc.ServeHTTP(0xc208100220, 0x7f2e30d47dd0, 0xc208116780, 0xc208278dd0)
        /usr/src/go/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208018d70, 0x7f2e30d47dd0, 0xc208116780, 0xc208278dd0)
        /go/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x292
net/http.serverHandler.ServeHTTP(0xc208106780, 0x7f2e30d47dd0, 0xc208116780, 0xc208278dd0)
        /usr/src/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208086680)
        /usr/src/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/src/go/src/pkg/net/http/server.go:1721 +0x313
```

**docker info**:

```
Containers: 4
Images: 35
Storage Driver: devicemapper
 Pool Name: docker-253:0-665100-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 780.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.6 GB
 Metadata Space Used: 1.982 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.17.4-1.el6.elrepo.x86_64
Operating System: <unknown>
CPUs: 2
Total Memory: 1.834 GiB

ID: 6IMJ:2P45:OG3M:CIC5:3LAJ:CD3D:KR47:BLYD:4IGX:6CNZ:B64M:KUED

WARNING: No swap limit support
```

**Comment by chanwit** [comment]
@vbichov have you got some typo? should it be `docker run` instead of `swarm run` ?

**Comment by vbichov** [comment]
@chanwit No, this is not a typo. This an alias for "docker -H tcp://swarm-host:swarm-ip"

**Comment by chanwit** [comment]
@vbichov OK. I got it.

**Comment by chanwit** [comment]
@vbichov which version of `swarm` you're using?

**Comment by vbichov** [comment]
@chanwit Swarm version was the latest in Docker Hub at the time of the original post.

**Comment by chanwit** [comment]
@vieux this is what I'm trying to fix in #769. 
`        /go/src/github.com/docker/swarm/scheduler/filter/affinity.go:37 +0xacc`

**Comment by chanwit** [comment]
@vbichov could you please post some steps to reproduce this bug?

After a discussion we've found that a container should always have its name, so this bug should not be happening.

**Comment by vbichov** [comment]
@chanwit I would love to, but I'm afraid there isn't much more to add.
I'm using the Consul for discovery.
got about 10 hosts connected, Swarm found them just fine.
(Update rate is slow, data may become stale, also how do you use the Swarm agent to de-register? - this is off topic...)
run the command above and that's it.
The filter is the problem: -e affinity:container!="registrator*"
That's it.

**Comment by aluzzardi** [comment]
@vbichov Did you hit this problem again?

**Comment by vbichov** [comment]
@aluzzardi using swarm:0.3.0-rc2 this problem has been resolved. (well done!)
By using running numbers for container names I can now try to mimic global scheduling...
Thank you!
